### PR TITLE
For UNK chars inside token

### PR DESCRIPTION
**Pull request by KoichiYasuoka**
and python 3.6 support for Google Colaboratories

### CODE REVIEW

**Comment by yzhangcs** [comment]
Great! Thanks for the contribution.

**Comment by KoichiYasuoka** [comment]
Thank you @yzhangcs for merging this PR, and do you have a plan to update the pip release of [SuPar](https://pypi.org/project/supar/)?

**Comment by yzhangcs** [comment]
@KoichiYasuoka Yeah, but not recently, since I'm still working for the implementation of MFVI&LBP for dependency parsing and some other features like integrating tokenizers. Currently I'm busy preparing my paper, I think the next release, SuPar v1.1.0, can be available around the Chinese New Year.

**Comment by KoichiYasuoka** [comment]
I'm very eager to see new PyPI release (even v.1.0.1), but I will wait for you @yzhangcs...

**Comment by yzhangcs** [comment]
@KoichiYasuoka Sorry for the late reply. Thank you for your attention to this package, and I will release the next version as soon as possible.
There're still some exps and code in progress. Very glad if you'd like to make any PRs.

**Pull request merged**
