### PR TITLE
rebalance kmeans clusters

### PR DESCRIPTION
**Pull request by attardi**
kmeans() sometimes produces large clusters, which cause to run out of CUDA memory when computing the embeddings.

The change is just in file parser/util/alg.py.

The other files contain unrelated changes, to allow using ELECTRA models or other from Huggingface.

### CODE REVIEW

**Comment by attardi** [comment]
Sorry, the requirements.txt should read:

transformers == 2.10.0

**Comment by yzhangcs** [comment]
> Sorry, the requirements.txt should read:
> 
> transformers == 2.10.0

Sorry, the code does not support transformers with version 2.2 or higher right now.
Since I employ a word-wise tokenization for BERT input, and `BertTokenizer.encode` adds special tokens like `[PAD]` and `[SEP]` to each tokenized unit by default since 2.2.
This can lead to some unexpected behavior.

**Comment by attardi** [comment]
These are formatting errors.
Shall I close this and resubmit?

**Comment by attardi** [comment]
It does not work as expected.

**Pull request closed without merging**
